### ISSUE TITLE
Add support for Shelly Plus H&T

### ISSUE THREAD

**Issue by JockeJ0** [sbender9/signalk-shelly#38]
Please add support for Shelly **Plus** H&T:
https://www.shelly.cloud/en/products/shop/shelly-plus-h-and-t

Thanks!

**Comment by ivanlofgren** [comment]
aye, yes please. +1 Thanks

**Comment by sbender9** [comment]
Sorry! I totally missed this!

**Comment by sbender9** [comment]
I released this. Please test and let me know!

**Comment by JockeJ0** [comment]
Excellent, thanks! Will test next time in the boat

**Comment by ivanlofgren** [comment]
Hi Scott,

Can't get it all to work at all. Removed all the Shellies upon first boot, since I was connected to the wrong wifi (50 shellies from home instead of boat). Now I can't get the addon to discover any devices - new or old.

I can see that the devices are being discovered in the log, but they aren't added to the interface.
E.g LOG: "Aug 21 10:32:38 2023-08-21T08:32:38.418Z signalk-shelly discovered device B9F8A0 SHSW-1 @ 192.168.1.138".

The above device is a Shelly H&T (not plus), so should be working.


Is there a way to reset all the removed devices so that the automatically populate the list again?
I have no password for my shelly units, so the manual adding using device-id and pwd doesn't work either.

Please advice, really appriciate the addon, the help and all the time you've put into this 🙂


Regards,
Ivan
________________________________
Från: Scott Bender ***@***.***>
Skickat: den 12 augusti 2023 08:31
Till: sbender9/signalk-shelly ***@***.***>
Kopia: ivanlofgren ***@***.***>; Comment ***@***.***>
Ämne: Re: [sbender9/signalk-shelly] Add support for Shelly Plus H&T (Issue #38)


I released this. Please test and let me know!
